---
functional:
  - посетителям игровой площадки должна предоставляться возможность играть баттлы без регистрации
  - у посетителей должна быть возможность создавать учётные записи игроков
  - у игроков должна быть возможность для баттлов не только с другими игроками, но и с ботами (исключаются субъективные факторы)
  - при выборе баттла игрок должен иметь возможность выбирать его сложность и удобный для себя язык программирования
  - игрок имеет собственный рейтинг, зависящий от количества сыгранных баттлов и других показателей активности на игровой площадке
  - игрок участвует в рейтинговых таблицах наравне с другими игроками, эти таблицы отображаются на главной странице игровой площадки
  - игрок должен иметь возможность создавать собственные баттлы
  - игрок должен иметь возможность общаться с другими игроками (внутренний чат площадки, Дискорд)
  - игрок должен иметь возможность приглашать других игроков на баттлы
  - игрок имеет возможность просматривать текущие либо прошедшие баттлы в реальном времени либо в записи
  - игровая площадка отображает состояние текущих баттлов, историю баттлов, количество игроков онлайн, беседы во внутреннем чате и рейтинговую таблицу игроков
  - в таблице текущих баттлов (Lobby) указывается информация о каждом баттле и линки на просмотр прошедшего/текущего баттла, а также на присоединение к баттлу, ждущему игроков
  - история баттлов отображается в обратной хронологической последовательности, показывается сложность, никнеймы игроков, дата баттла и линк на его просмотр  
  - игровая площадка предоставляет игрокам возможность участвовать в турнирах (баттлы между более чем двумя игроками)
  - на главной странице отображается рейтинговая таблица лучших игроков
  - при создании собственного баттла есть возможность выбрать его сложность, соперника в баттле (игрок, друг, бот), установку контроля времени, проблему, решаемую в ходе баттла
  - после создания баттла в игровом поле имеется - возможность выбора языка программирования, окно редактора для ввода кода решения со "скелетом" программы на выбранном ЯП, кнопка сброса редактора в исходное состояние, кнопка проверки решения с выводом результатов проверки
  - в процессе баттла каждому игроку показывается процесс кодирования, происходящий в редакторе соперника
  - в случае проигрыша игроку предоставляется возможность "быстрой" переигровки без выхода с игрового поля
non-functional:
  - игровая площадка предоставляет как собственные средства регистрации/аутентификации игроков, так и сторонние 
  - сайт игровой площадки (СИП) имеет "дневные" и "ночные" темы оформления
  - СИП адаптирован для показа на мобильных устройствах
  - СИП выдерживает большое количество посетителей (1000+)
  - при использовании собственных средств аутентификации СИП обеспечивает защищённость хранения личной информации пользователей и обмена ею
implicit:
  - при регистрации через сторонний сервис в учётную запись игрока импортируется фотография и никнейм из стороннего сервиса 
  - при пропадании связи не должна пропадать возможность доигрывания уже начатого баттла
  - в составлении рейтинга игрока участвует соотношение выигранных им баттлов к проигранным
  - в таблице Lobby указывается сложность каждого баттла, его состояние (играется либо ждёт игроков), никнеймы участников, наличие/отсутствие зачётного рейтинга
  - в рейтинговой таблице игроков есть опции просмотра за неделю, месяц и за всё время фиксации баттлов на площадке
  - таблица рейтингов, таблица текущих баттлов, количество игроков онлайн и таблица турниров обновляются в режиме реального времени
  - история баттлов отображается в виде прокручиваемого списка с конечным числом строк. при прокрутке до конца списка авотматически подгружается его следующая часть
  - при наведении мышью на никнейме игрока высвечивается информация о выигранных/проиранных баттлах и бейджи-награды за достигнутые успехи
  - в качестве соперников в баттлах, ждущих игроков, выступают боты. Если играемых баттлов в данный момент нет, ждущие баттлы варьируются по языкам программирования и по сложности
  - у игроков есть возможность принудительно закончить баттл, не дожидаясь истечения его времени, т.е. "сдаться" (Give Up)
