---
functional:
  - посетителям игровой площадки должна предоставляться возможность играть баттлы без регистрации
  - у посетителей должна быть возможность создавать учётные записи игроков
  - у игроков должна быть возможность для баттлов не только с другими игроками, но и с ботами
  - при выборе баттла игрок должен иметь возможность выбирать его сложность и удобный для себя язык программирования
  - игрок имеет собственный рейтинг, зависящий от количества сыгранных баттлов и других показателей активности на игровой площадке
  - игрок участвует в рейтинговых таблицах наравне с другими игроками, эти таблицы отображаются на главной странице игровой площадки
  - игрок должен иметь возможность создавать собственные баттлы
  - игрок должен иметь возможность общаться с другими игроками (внутренний чат площадки, Дискорд)
  - игрок должен иметь возможность приглашать других игроков на баттлы
  - игрок имеет возможность просматривать текущие либо прошедшие баттлы в реальном времени либо в записи
  - игровая площадка отображает состояние текущих баттлов, количество игроков онлайн, беседы во внутреннем чате и рейтинговую таблицу игроков в режиме реального времени
  - в таблице текущих баттлов (Lobby) указывается сложность каждого баттла, его состояние (играется либо ждёт игроков), никнеймы участников, наличие/отсутствие рейтинга, а также возможность присоединения к баттлу либо его просмотра 
  - игровая площадка предоставляет игрокам возможность участвовать в турнирах (баттлы между более чем двумя игроками)
  - рейтинговая таблица отображает лучших игроков недели, месяца и за всё время
  - при создании собственного баттла есть возможность выбрать его сложность, соперника в баттле (игрок, друг, бот), установку контроля времени, проблему, решаемую в ходе баттла
  - после создания баттла в игровом поле имеется - возможность выбора языка программирования, окно редактора для ввода кода решения со "скелетом" программы на выбранном ЯП, кнопка сброса редактора в исходное состояние, кнопка проверки решения с выводом результатов проверки
  - в процессе баттла каждому игроку показывается процесс кодирования, происходящий в редакторе соперника
  - в случае проигрыша игроку предоставляется возможность "быстрой" переигровки без выхода с игрового поля
non-functional:
  - игровая площадка предоставляет как собственные средства регистрации/аутентификации игроков, так и сторонние 
  - сайт игровой площадки (СИП) имеет "дневные" и "ночные" темы оформления
  - СИП адаптирован для показа на мобильных устройствах
  - СИП выдерживает большое количество посетителей
implicit:
  - при пропадании связи не должна пропадать возможность доигрывания уже начатого баттла
